services:
  api:
    container_name: Aberta.API
    build:
      context: ./Aberta/Test/Aberta.API/.
    ports:
      - 8081:8080
    volumes:
      - ./Aberta/Test/Aberta.API/wwwroot:/App/wwwroot
      - ./Aberta/Test/Aberta.API/Logs:/App/Logs
      - ./Aberta/Test/Aberta.API/Keys:/root/.aspnet/DataProtection-Keys
  scanner:
    container_name: Aberta.Scanner
    build:
      context: ./Aberta/Test/Aberta.Scanner/.
    ports:
      - 8083:8080
    depends_on:
      - hangfire
  backoffice:
    container_name: Aberta.BackOffice
    build:
      context: ./Aberta/Test/Aberta.BackOffice/.
    ports:
      - 8082:8080
    volumes:
      - ./Aberta/Test/Aberta.BackOffice/db:/App/Data
      - ./Aberta/Test/Aberta.BackOffice/Keys:/root/.aspnet/DataProtection-Keys
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
  mariadb:
    image: mariadb:11.2
    container_name: Aberta.DB
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./Aberta/Test/Aberta.API/db/initdb.d/:/docker-entrypoint-initdb.d/
    ports:
      - "${MARIADB_PORT}:3306"
  sqlserver:
    container_name: Aberta.SqlServer
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"