services:
  db:
    image: mariadb:11.2
    container_name: Aberta.DB
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - ./API/db/initdb.d/:/docker-entrypoint-initdb.d/
    ports:
      - "${MARIADB_PORT}:3306"
    restart: 'unless-stopped'
  api:
    container_name: Aberta.API
    build:
      context: ./API/.
    ports:
      - 8081:8080
    volumes:
      - ./API/wwwroot:/App/wwwroot
      - ./API/Logs:/App/Logs
      - ./API/Keys:/root/.aspnet/DataProtection-Keys
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: 'unless-stopped'
  scanner:
    container_name: Aberta.Scanner
    build:
      context: ./Scanner/.
    volumes:
      - ./Scanner/Logs:/App/Logs
      - ./Scanner/Keys:/root/.aspnet/DataProtection-Keys
    ports:
      - 8083:8080
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: 'unless-stopped'
  backoffice:
    container_name: Aberta.BackOffice
    build:
      context: ./BackOffice/.
    ports:
      - 8082:8080
    volumes:
      - ./BackOffice/db:/App/Data
      - ./BackOffice/Keys:/root/.aspnet/DataProtection-Keys
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: 'unless-stopped'