services:
  scanner:
    container_name: scanner
    build:
      context: .
    ports:
      - 8081:8080
    depends_on:
      - hangfire
  hangfire:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "P4sSw0+rd@-"
      ACCEPT_EULA: "Y"